#index:
#    path: /
#    controller: App\Controller\DefaultController::index

new_intervenant_success:
  path:         /dashboard/intervenants
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template:   'dashboard/secretaire/intervenant/listeintervenant.html.twig'
    maxAge:     86400
    sharedAge:  86400

remove_intervenant_success:
  path:         /dashboard/intervenants
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template:   'dashboard/secretaire/intervenant/listeintervenant.html.twig'
    maxAge:     86400
    sharedAge:  86400

modify_intervenant_success:
  path: /dashboard/intervenants
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'dashboard/secretaire/intervenant/listeintervenant.html.twig'
    maxAge: 86400
    sharedAge: 86400

remove_matiere_success:
  path: /dashboard/matieres
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'dashboard/secretaire/matiere/listematieres.html.twig'
    maxAge: 86400
    sharedAge: 86400

modify_matiere_success:
  path: /dashboard/matieres
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'dashboard/secretaire/matiere/listematieres.html.twig'
    maxAge: 86400
    sharedAge: 86400

new_matiere_success:
  path: /dashboard/matieres
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'dashboard/secretaire/matiere/listematieres.html.twig'
    maxAge: 86400
    sharedAge: 86400

modify_calendar_success:
  path: /dashboard/parametre/calendrier
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'dashboard/secretaire/parametre/calendrier.html.twig'
    maxAge: 86400
    sharedAge: 86400

new_etudiant_success:
  path: /dashboard/etudiants
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'dashboard/secretaire/etudiant/listeetudiant.html.twig'
    maxAge: 86400
    sharedAge: 86400

remove_etudiant_success:
  path: /dashboard/etudiants
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'dashboard/secretaire/etudiant/listeetudiant.html.twig'
    maxAge: 86400
    sharedAge: 86400

modify_etudiant_success:
  path: /dashboard/etudiants
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'dashboard/secretaire/etudiant/listeetudiant.html.twig'
    maxAge: 86400
    sharedAge: 86400

new_groupe_success:
  path: /dashboard/groupes
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'dashboard/secretaire/groupe/listegroupe.html.twig'
    maxAge: 86400
    sharedAge: 86400

remove_groupe_success:
  path: /dashboard/groupes
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'dashboard/secretaire/groupe/listegroupe.html.twig'
    maxAge: 86400
    sharedAge: 86400

new_cours_success:
  path: /dashboard/calendrier
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'dashboard/secretaire/calendrier/calendrier.html.twig'
    maxAge: 86400
    sharedAge: 86400